import type { ResultSet } from '../../../types';
import type { ColumnBridgeable } from '../interfaces/ColumnBridgeable';
import type { QueryBridgeable } from '../interfaces/QueryBridgeable';
import { executeAsyncWithPolling } from './asyncPolling';

export const PAGE_SIZE = 10000;

/** Strip TOP N / LIMIT N from SQL generated by buildDataViewSql to get a base SQL for pagination */
export function toBaseSql(sql: string): string {
  return sql
    .replace(/^(\s*SELECT\s+)TOP\s+\d+\s+/i, '$1')
    .replace(/\s+LIMIT\s+\d+\s*$/i, '');
}

export async function fetchTableWithComments(
  bridge: QueryBridgeable & ColumnBridgeable,
  connectionId: string,
  tableName: string,
  sql: string,
  signal?: AbortSignal,
  timeoutMs?: number
): Promise<ResultSet> {
  const [columnDefinitions, pollResult] = await Promise.all([
    bridge.getColumns(connectionId, tableName),
    executeAsyncWithPolling(bridge, connectionId, sql, signal, undefined, timeoutMs),
  ]);

  if (pollResult.multipleResults) {
    throw new Error('Unexpected multiple results for data view query');
  }
  const result = pollResult;

  const colDefMap = new Map(columnDefinitions.map((col) => [col.name, col]));

  const isTruncated = result.truncated || result.rows.length > PAGE_SIZE;
  const displayRows =
    result.rows.length > PAGE_SIZE ? result.rows.slice(0, PAGE_SIZE) : result.rows;

  return {
    columns: result.columns.map((c) => {
      const def = colDefMap.get(c.name);
      return {
        name: c.name,
        type: c.type,
        size: def?.size ?? 0,
        nullable: def?.nullable ?? true,
        isPrimaryKey: def?.isPrimaryKey ?? false,
        comment: def?.comment || undefined,
      };
    }),
    rows: displayRows,
    affectedRows: result.affectedRows,
    executionTimeMs: result.executionTimeMs,
    truncated: isTruncated,
  };
}
